project_id = "rzekncwnwtgtwinesjyl"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[functions.scrape-events]
verify_jwt = false

[functions.parse-playlist]
verify_jwt = false

[functions.fetch-instagram]
verify_jwt = false

[functions.analyze-playlist-dna]
verify_jwt = false

[functions.fetch-global-events]
verify_jwt = false

[functions.enrich-artist]
verify_jwt = false