// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzekncwnwtgtwinesjyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6ZWtuY3dud3RndHdpbmVzanlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc1NTc0NjMsImV4cCI6MjA4MzEzMzQ2M30.bRignUhT4I8pWsp1lqpzC-FFJ7nkL7h4Gwlmq-sj1Ds";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
